### ISSUE TITLE
PHP unit tests crashed on PHP 7.*

### ISSUE THREAD

**Issue by shinfan** [googleapis/api-client-staging#373]
Error message:
root@c206340828e2:/api-client-staging# ./vendor/bin/phpunit 

Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /api-client-staging/vendor/google/gax/src/Testing/GeneratedTest.php on line 36

**Comment by michaelbausor** [comment]
Fixed in https://github.com/googleapis/api-client-staging/pull/375
